### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by josepot** [re-rxjs/re-rxjs#41]
I think that we've almost at a point where I would feel good releasing `v0.2.0` of this library.

Things that I would like to discuss before `v0.2.0` is released:

- I've got used to the name `distinctShareReplay`, but I hate it. I think that it's a horrible name... I'm actually considering the idea of coining a term for the kind of Observable that it generates (like `BehaviorObservable` or `ReactObservable` or WHATEVER) and then renaming the operator to something like `asReactObservable` or `asBehaviorObservable`.

I'm also starting to wonder whether this operator should be exposed in the first place... But I think that it should. Because we know from experience that if we don't expose it, then most of the users of this library will have to create their own custom `shareReplay`, and the worst part is that it's not even possible to create the custom `shareReplay` that would work best with this library by using any of the overloads of the current RxJS `shareReplay`... So, yeah, I think that it should be exposed, but not with that name... Also, maybe we should only export the "customShareReplay" behavior without the `distinct`? and then we could simply call it `shareLatest`? :thinking: Or maybe we could just name it `shareLatest` and that's it (with the distinct behavior still on it)?

I won't release `v0.2.0` until I'm not happy with this.

There are 2 other things that I would like to happen before we release `v0.2.0`:

1) use docosaurus to generate a site for https://re-rxjs.org or for https://rerxjs.org (I bought both domains). Ideally I would like to have in that site similar to the one that recoil.js has, at least with the following sections:
- Introduction
- Basic Tutorial
- API Reference

2) A blog-post announcing the release of this library.

I've been working on those 2 items, but I will need help... I will create separate issues for those 2. Oh, the docs-site would live under a completely different repo.

**Comment by voliva** [comment]
That's a nice discussion. On distinctShareReplay, I also wondered the same thing. Is it really needed if people can use `connectObservable` or `connectFactoryObservable` and get the "distinctShareReplay"ed observable that can be used to build other streams?

What's the use case where distinctShareReplay would be useful for a consumer?

If we expose it, I like `shareLatest` name, but I wouldn't make it apply `distinctUntilChanged`. From a consumer PoV the useful bit of `shareLatest` would be on how it shares the source stream - distinctUntilChanged can be added if needed.

**Comment by josepot** [comment]
I've been thinking a lot about this and I think that I've finally realized what the issue is here. I will try to summarize it:
- The `distinctUntilChanged` behavior should not be baked into the current `distinctUntilChanged`
- `connectObservable` and `connectFactoryObservable` should not take the `compareFn` option at all.
- The internal `react-enhancer` can (and should) apply a `distinctUntilChanged(Object.is)` in order to prevent unnecessary `React.setState` calls.
- An enhancer that we could name `shareLatest` could (and I think that should) be exposed, and its behavior would be the equivalent of:

```ts
const shareLatest = <T>() => (
  source$: Observable<T>,
): Observable<T> =>
  source$.pipe(
    multicast(() => new ReplaySubject<T>(1)),
    refCount(),
  )
```

I'm working on that... I can't wait to get that done!

**Comment by voliva** [comment]
Go for it, sounds good 🎉. The distinct part makes sense to only apply in the react hook.

**Comment by josepot** [comment]
I'm closing this because I'm really happy with the latest alpha release. I will create separate issues for the other stuff. Also, I will try to make those issues more organized (and less chaotic).
